/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected/route'
import { Route as IndexImport } from './routes/index'
import { Route as InviteCodeImport } from './routes/invite/$code'
import { Route as ProtectedSettingsImport } from './routes/_protected/settings'
import { Route as ProtectedHomeImport } from './routes/_protected/home'
import { Route as ProtectedBoardsCreateImport } from './routes/_protected/boards/create'
import { Route as ProtectedBoardsBoardIdImport } from './routes/_protected/boards/$boardId'
import { Route as ProtectedBoardsBoardIdEditImport } from './routes/_protected/boards/$boardId/edit'
import { Route as ProtectedBoardsBoardIdCollaboratorsImport } from './routes/_protected/boards/$boardId/collaborators'
import { Route as ProtectedBoardsBoardIdTasksTaskIdImport } from './routes/_protected/boards/$boardId.tasks/$taskId'

// Create/Update Routes

const ProtectedRouteRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const InviteCodeRoute = InviteCodeImport.update({
  id: '/invite/$code',
  path: '/invite/$code',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedSettingsRoute = ProtectedSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedHomeRoute = ProtectedHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedBoardsCreateRoute = ProtectedBoardsCreateImport.update({
  id: '/boards/create',
  path: '/boards/create',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedBoardsBoardIdRoute = ProtectedBoardsBoardIdImport.update({
  id: '/boards/$boardId',
  path: '/boards/$boardId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

const ProtectedBoardsBoardIdEditRoute = ProtectedBoardsBoardIdEditImport.update(
  {
    id: '/edit',
    path: '/edit',
    getParentRoute: () => ProtectedBoardsBoardIdRoute,
  } as any,
)

const ProtectedBoardsBoardIdCollaboratorsRoute =
  ProtectedBoardsBoardIdCollaboratorsImport.update({
    id: '/collaborators',
    path: '/collaborators',
    getParentRoute: () => ProtectedBoardsBoardIdRoute,
  } as any)

const ProtectedBoardsBoardIdTasksTaskIdRoute =
  ProtectedBoardsBoardIdTasksTaskIdImport.update({
    id: '/tasks/$taskId',
    path: '/tasks/$taskId',
    getParentRoute: () => ProtectedBoardsBoardIdRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRoute
    }
    '/_protected/home': {
      id: '/_protected/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedHomeImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/invite/$code': {
      id: '/invite/$code'
      path: '/invite/$code'
      fullPath: '/invite/$code'
      preLoaderRoute: typeof InviteCodeImport
      parentRoute: typeof rootRoute
    }
    '/_protected/boards/$boardId': {
      id: '/_protected/boards/$boardId'
      path: '/boards/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof ProtectedBoardsBoardIdImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/boards/create': {
      id: '/_protected/boards/create'
      path: '/boards/create'
      fullPath: '/boards/create'
      preLoaderRoute: typeof ProtectedBoardsCreateImport
      parentRoute: typeof ProtectedRouteImport
    }
    '/_protected/boards/$boardId/collaborators': {
      id: '/_protected/boards/$boardId/collaborators'
      path: '/collaborators'
      fullPath: '/boards/$boardId/collaborators'
      preLoaderRoute: typeof ProtectedBoardsBoardIdCollaboratorsImport
      parentRoute: typeof ProtectedBoardsBoardIdImport
    }
    '/_protected/boards/$boardId/edit': {
      id: '/_protected/boards/$boardId/edit'
      path: '/edit'
      fullPath: '/boards/$boardId/edit'
      preLoaderRoute: typeof ProtectedBoardsBoardIdEditImport
      parentRoute: typeof ProtectedBoardsBoardIdImport
    }
    '/_protected/boards/$boardId/tasks/$taskId': {
      id: '/_protected/boards/$boardId/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/boards/$boardId/tasks/$taskId'
      preLoaderRoute: typeof ProtectedBoardsBoardIdTasksTaskIdImport
      parentRoute: typeof ProtectedBoardsBoardIdImport
    }
  }
}

// Create and export the route tree

interface ProtectedBoardsBoardIdRouteChildren {
  ProtectedBoardsBoardIdCollaboratorsRoute: typeof ProtectedBoardsBoardIdCollaboratorsRoute
  ProtectedBoardsBoardIdEditRoute: typeof ProtectedBoardsBoardIdEditRoute
  ProtectedBoardsBoardIdTasksTaskIdRoute: typeof ProtectedBoardsBoardIdTasksTaskIdRoute
}

const ProtectedBoardsBoardIdRouteChildren: ProtectedBoardsBoardIdRouteChildren =
  {
    ProtectedBoardsBoardIdCollaboratorsRoute:
      ProtectedBoardsBoardIdCollaboratorsRoute,
    ProtectedBoardsBoardIdEditRoute: ProtectedBoardsBoardIdEditRoute,
    ProtectedBoardsBoardIdTasksTaskIdRoute:
      ProtectedBoardsBoardIdTasksTaskIdRoute,
  }

const ProtectedBoardsBoardIdRouteWithChildren =
  ProtectedBoardsBoardIdRoute._addFileChildren(
    ProtectedBoardsBoardIdRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedHomeRoute: typeof ProtectedHomeRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedBoardsBoardIdRoute: typeof ProtectedBoardsBoardIdRouteWithChildren
  ProtectedBoardsCreateRoute: typeof ProtectedBoardsCreateRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedHomeRoute: ProtectedHomeRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedBoardsBoardIdRoute: ProtectedBoardsBoardIdRouteWithChildren,
  ProtectedBoardsCreateRoute: ProtectedBoardsCreateRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/settings': typeof ProtectedSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/boards/$boardId': typeof ProtectedBoardsBoardIdRouteWithChildren
  '/boards/create': typeof ProtectedBoardsCreateRoute
  '/boards/$boardId/collaborators': typeof ProtectedBoardsBoardIdCollaboratorsRoute
  '/boards/$boardId/edit': typeof ProtectedBoardsBoardIdEditRoute
  '/boards/$boardId/tasks/$taskId': typeof ProtectedBoardsBoardIdTasksTaskIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof ProtectedRouteRouteWithChildren
  '/home': typeof ProtectedHomeRoute
  '/settings': typeof ProtectedSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/boards/$boardId': typeof ProtectedBoardsBoardIdRouteWithChildren
  '/boards/create': typeof ProtectedBoardsCreateRoute
  '/boards/$boardId/collaborators': typeof ProtectedBoardsBoardIdCollaboratorsRoute
  '/boards/$boardId/edit': typeof ProtectedBoardsBoardIdEditRoute
  '/boards/$boardId/tasks/$taskId': typeof ProtectedBoardsBoardIdTasksTaskIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_protected/home': typeof ProtectedHomeRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/invite/$code': typeof InviteCodeRoute
  '/_protected/boards/$boardId': typeof ProtectedBoardsBoardIdRouteWithChildren
  '/_protected/boards/create': typeof ProtectedBoardsCreateRoute
  '/_protected/boards/$boardId/collaborators': typeof ProtectedBoardsBoardIdCollaboratorsRoute
  '/_protected/boards/$boardId/edit': typeof ProtectedBoardsBoardIdEditRoute
  '/_protected/boards/$boardId/tasks/$taskId': typeof ProtectedBoardsBoardIdTasksTaskIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/home'
    | '/settings'
    | '/invite/$code'
    | '/boards/$boardId'
    | '/boards/create'
    | '/boards/$boardId/collaborators'
    | '/boards/$boardId/edit'
    | '/boards/$boardId/tasks/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/home'
    | '/settings'
    | '/invite/$code'
    | '/boards/$boardId'
    | '/boards/create'
    | '/boards/$boardId/collaborators'
    | '/boards/$boardId/edit'
    | '/boards/$boardId/tasks/$taskId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/home'
    | '/_protected/settings'
    | '/invite/$code'
    | '/_protected/boards/$boardId'
    | '/_protected/boards/create'
    | '/_protected/boards/$boardId/collaborators'
    | '/_protected/boards/$boardId/edit'
    | '/_protected/boards/$boardId/tasks/$taskId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  InviteCodeRoute: typeof InviteCodeRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  InviteCodeRoute: InviteCodeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_protected",
        "/invite/$code"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_protected": {
      "filePath": "_protected/route.tsx",
      "children": [
        "/_protected/home",
        "/_protected/settings",
        "/_protected/boards/$boardId",
        "/_protected/boards/create"
      ]
    },
    "/_protected/home": {
      "filePath": "_protected/home.tsx",
      "parent": "/_protected"
    },
    "/_protected/settings": {
      "filePath": "_protected/settings.tsx",
      "parent": "/_protected"
    },
    "/invite/$code": {
      "filePath": "invite/$code.tsx"
    },
    "/_protected/boards/$boardId": {
      "filePath": "_protected/boards/$boardId.tsx",
      "parent": "/_protected",
      "children": [
        "/_protected/boards/$boardId/collaborators",
        "/_protected/boards/$boardId/edit",
        "/_protected/boards/$boardId/tasks/$taskId"
      ]
    },
    "/_protected/boards/create": {
      "filePath": "_protected/boards/create.tsx",
      "parent": "/_protected"
    },
    "/_protected/boards/$boardId/collaborators": {
      "filePath": "_protected/boards/$boardId/collaborators.tsx",
      "parent": "/_protected/boards/$boardId"
    },
    "/_protected/boards/$boardId/edit": {
      "filePath": "_protected/boards/$boardId/edit.tsx",
      "parent": "/_protected/boards/$boardId"
    },
    "/_protected/boards/$boardId/tasks/$taskId": {
      "filePath": "_protected/boards/$boardId.tasks/$taskId.tsx",
      "parent": "/_protected/boards/$boardId"
    }
  }
}
ROUTE_MANIFEST_END */
