/**
 * WebSocket board event types, mirroring the backend's BoardEventType enum.
 */
export const BoardEventType = {
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_MOVED: "TASK_MOVED",
  TASK_DELETED: "TASK_DELETED",
  BOARD_UPDATED: "BOARD_UPDATED",
  COLUMN_CREATED: "COLUMN_CREATED",
  COLUMN_UPDATED: "COLUMN_UPDATED",
  COLUMN_DELETED: "COLUMN_DELETED",
  COLUMN_MOVED: "COLUMN_MOVED",
  LABEL_CREATED: "LABEL_CREATED",
  LABEL_UPDATED: "LABEL_UPDATED",
  LABEL_DELETED: "LABEL_DELETED",
  COMMENT_ADDED: "COMMENT_ADDED",
  COMMENT_UPDATED: "COMMENT_UPDATED",
  COMMENT_DELETED: "COMMENT_DELETED",
  ACTIVITY_LOGGED: "ACTIVITY_LOGGED",
  CHECKLIST_ITEM_ADDED: "CHECKLIST_ITEM_ADDED",
  CHECKLIST_ITEM_UPDATED: "CHECKLIST_ITEM_UPDATED",
  CHECKLIST_ITEM_DELETED: "CHECKLIST_ITEM_DELETED",
  CHECKLIST_ITEM_REORDERED: "CHECKLIST_ITEM_REORDERED",
} as const;

export type BoardEventType =
  (typeof BoardEventType)[keyof typeof BoardEventType];
