/**
 * Activity log types, mirroring the backend's ActivityType enum.
 */
export const ActivityType = {
  TASK_CREATED: "TASK_CREATED",
  TASK_UPDATED: "TASK_UPDATED",
  TASK_MOVED: "TASK_MOVED",
  TASK_DELETED: "TASK_DELETED",
  TASK_COMPLETED: "TASK_COMPLETED",
  TASK_REOPENED: "TASK_REOPENED",
  TASK_ARCHIVED: "TASK_ARCHIVED",
  TASK_UNARCHIVED: "TASK_UNARCHIVED",
  ASSIGNEE_CHANGED: "ASSIGNEE_CHANGED",
  LABELS_CHANGED: "LABELS_CHANGED",
  PRIORITY_CHANGED: "PRIORITY_CHANGED",
  DUE_DATE_CHANGED: "DUE_DATE_CHANGED",
  COLUMN_CREATED: "COLUMN_CREATED",
  COLUMN_UPDATED: "COLUMN_UPDATED",
  COLUMN_DELETED: "COLUMN_DELETED",
  COLUMN_MOVED: "COLUMN_MOVED",
  COLUMN_ARCHIVED: "COLUMN_ARCHIVED",
  COLUMN_RESTORED: "COLUMN_RESTORED",
  CHECKLIST_ITEM_ADDED: "CHECKLIST_ITEM_ADDED",
  CHECKLIST_ITEM_COMPLETED: "CHECKLIST_ITEM_COMPLETED",
  CHECKLIST_ITEM_UNCOMPLETED: "CHECKLIST_ITEM_UNCOMPLETED",
  CHECKLIST_ITEM_UPDATED: "CHECKLIST_ITEM_UPDATED",
  CHECKLIST_ITEM_DELETED: "CHECKLIST_ITEM_DELETED",
} as const;

export type ActivityType = (typeof ActivityType)[keyof typeof ActivityType];
