package com.kylerriggs.kanban.activity;

public enum ActivityType {
    TASK_CREATED,
    TASK_UPDATED,
    TASK_MOVED,
    TASK_DELETED,
    TASK_COMPLETED,
    TASK_REOPENED,
    TASK_ARCHIVED,
    TASK_UNARCHIVED,
    ASSIGNEE_CHANGED,
    LABELS_CHANGED,
    PRIORITY_CHANGED,
    DUE_DATE_CHANGED,
    COLUMN_CREATED,
    COLUMN_UPDATED,
    COLUMN_DELETED,
    COLUMN_MOVED,
    COLUMN_ARCHIVED,
    COLUMN_RESTORED,
    CHECKLIST_ITEM_ADDED,
    CHECKLIST_ITEM_COMPLETED,
    CHECKLIST_ITEM_UNCOMPLETED,
    CHECKLIST_ITEM_UPDATED,
    CHECKLIST_ITEM_DELETED
}
